//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5120_Project_Refugees.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RefugeeDatabaseEntities : DbContext
    {
        public RefugeeDatabaseEntities()
            : base("name=RefugeeDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COUNTRY> COUNTRies { get; set; }
        public virtual DbSet<SPORT> SPORTs { get; set; }
        public virtual DbSet<TERM> TERMs { get; set; }
    }
}
