// <auto-generated />
namespace FIT5120_Project_Refugees.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FirstMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202104231412389_First-Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
